version: '3.8'

services:
  mongo:
    image: mongo:6.0.5
    container_name: sleepr_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
