version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - sleepr
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    networks:
      - sleepr
  mongo:
    image: mongo:6.0.5
    container_name: sleepr_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - sleepr

networks:
  sleepr:
    driver: bridge
